version: "3.5"
services:
  cassandra:
    image: cassandra:latest
    hostname: cassandra-docker
    ports:
      - "9042:9042"
    volumes:
      - "cassandra_data:/var/lib/cassandra"
    #networks:
    #  - backend

#networks:
#  backend:

volumes:
  cassandra_data:
